### ISSUE TITLE
Bug in getDateFormat in utils.js

### ISSUE THREAD

**Issue by nymoen** [Esri/crowdsource-manager#84] opened 2015-10-15 09:35 UTC
I have been using the Crowdsource Manager app in ArcGIS Online. And it does not respect the dateformat I set up in the popup.
 It is a format bug in the code.
The code is: case "shortDateLEShortTime24":
                obj.dateFormat = "MM/DD/YYYY HH:mm";

The format of shortDateLEShortTime24 should be DD/MM/YYYY HH:mm

Regards
Kjetil Nymoen

**Comment by allisonmuise** [comment] 2015-10-16 18:17
@nymoen : Could you attach a screenshot of your popup configuration window?
Based on the description above, I am unable to reproduce your issue. I wonder if it's a specific combination of settings causing the issue.

**Comment by nymoen** [comment] 2015-10-19 06:49
Soory for not being very clear. Here is my popup config in the webmap on the field:
![image](https://cloud.githubusercontent.com/assets/8665669/10571274/fd4a5428-763d-11e5-809b-cab47a14ecf0.png)

And here you see the listview and popup in the crowdsource manager app bulit using ArcGIS Online: You can see that the format in the listview is wrong. It should show the same format as the popup.
![image](https://cloud.githubusercontent.com/assets/8665669/10571292/29c40558-763e-11e5-843b-e7f6e1b42a59.png)

**Comment by allisonmuise** [comment] 2015-10-19 21:47
@nymoen Thanks! That helped a lot. We'll get this fixed in the next release.

**Comment by allisonmuise** [comment] 2015-10-26 17:54
Verified fixed in dev environment

**Closed by allisonmuise** 2015-10-26 17:54 UTC
Labels: Assigned, Delivered
