### ISSUE TITLE
Popup doesnt show for non editable reference layers

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-manager#259] opened 2018-06-27 19:52 UTC
1. Create a map with editable layer
2. Add another non editable layer 
3. Configure manager app to 'Show Reference Layers' and to 'Show Popup for non-editable layers'.
4. Notice that popup doesn't show up when non editable layer feature is clicked

**Comment by pratikg** [comment] 2018-12-05 06:10
@allisonmuise,

We are unable to reproduce this issue and it's working correctly at our end as described below.

**_Step1: We created a webmap which contained editable & non-editable layers._**

![image](https://user-images.githubusercontent.com/1454356/49492896-1664b080-f880-11e8-8199-8ace1aa51097.png)

**_Step2: Configured "showPopupForNonEditableLayers" & "showNonEditableLayers" as true in the default.js file._**

![image](https://user-images.githubusercontent.com/1454356/49492937-2bd9da80-f880-11e8-8b21-284c552cbe5d.png)
![image](https://user-images.githubusercontent.com/1454356/49492944-35fbd900-f880-11e8-826c-9b8b213f0973.png)

**_Step3: Selected this webmap in the application, which didn't display "HSEC-Area Status" in the list but it got displayed on the map since its a non-editable layer._**

![image](https://user-images.githubusercontent.com/1454356/49492974-5461d480-f880-11e8-9e72-a7b5a634d5ee.png)

![image](https://user-images.githubusercontent.com/1454356/49493171-08635f80-f881-11e8-9929-d46487f27d14.png)

**_Step4: Selected 1 of the feature from the non-editable layer and observed that its details are displayed in the info panel._**

![image](https://user-images.githubusercontent.com/1454356/49493348-d0105100-f881-11e8-9b62-829eb9f60542.png)


Could you please provide us with the webmap/layers in which you are facing this issue.

**Comment by allisonmuise** [comment] 2018-12-06 02:22
I have seen this issue recently, but I'm unable to come up with a repro case right now so I'm not sure if there's a missing piece in the steps or if it's something that was resolved by changes elsewhere. I'll close and we can reopen if the issue reappears.

**Closed by allisonmuise** 2018-12-06 02:22 UTC
Labels: Bug
