### ISSUE TITLE
Android Tablet - Scrolling horizontally causes the header to lag behind the Observation List 

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/crowdsource-manager#56] opened 2015-05-08 17:26 UTC
Tested on Samsung Android Tablet (Galaxy 3) - device from test bank

Repro Steps
-Go to List View (happens in Split view too)
-Scroll Right in the Observation section
-Header is scolling slower than the list of records
(Header cannot catch up with the records during the scroll) 

This does not happen on in the Desktop Browsers.

**Comment by allisonmuise** [comment] 2015-05-11 18:38
@LindsayThomas  - What version of Android was this seen on?

**Comment by LindsayThomas** [comment] 2015-05-13 15:47
@allisonmuise Galaxy II (the version that is currently on the device in the Redland Solutions test bank.

**Comment by allisonmuise** [comment] 2015-05-13 17:06
@CTLocalGovTeam : Please investigate scrolling the title bar at the same rate as the table. The titles eventually catch up, but both title bar and rows should scroll at the same speed.

**Comment by allisonmuise** [comment] 2015-05-13 17:07
This is reproducible on Galaxy Tab 2 (Android 4.1.2) and Galaxy Tab S (4.4.2)

**Comment by CTLocalGovTeam** [comment] 2015-05-14 12:40
@allisonmuise, @LindsayThomas, 
The List View is drawn by a third party control named 'datatables' which is a JQuery (Javascript framework) plugin. The behavior of header lagging behind a few milliseconds while scrolling is something we noticed on all tablets (android as well as iPads). This may be due to the way the plugin generates separate UI controls for the header and the table below. We don't think we can fix this. 

This behavior can be observed on other sites too, where this plugin is used. 
E.g., you can try loading this url https://www.datatables.net/examples/basic_init/scroll_xy.html on any tablet (android/iPad) and observe the slight lag when you scroll horizontally.

**Comment by allisonmuise** [comment] 2015-05-14 17:16
ok. closing this issue.

**Closed by allisonmuise** 2015-05-14 17:16 UTC
Labels: Assigned, Medium, Sprint 2
