### ISSUE TITLE
Add support for manager to consume the grouped layers in new map viewer.

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-manager#355] opened 2022-11-16 22:35 UTC
When a user adds a feature service with multiple layers in it, the new map viewer adds it as a group layer and it throws an error when consumed in crowdsource manager app. 

Steps:

1. In the new map viewer - Add a feature service from the content or as a URL. Ensure the layer has multiple layers in it  Ex: https://servicesdev.arcgis.com/fEmgGq7yFGAFozS4/arcgis/rest/services/Reporter/FeatureServer
2. Save, and share with a group
3. Create a manager app from Group
4. Notice the error message "Configured group is invalid or no items have been shared with this group yet" 
5.  Repeat the process with the classic map viewer and there is no issue.

App https://localgovdev.mapsdevext.arcgis.com/apps/CrowdsourceManager/index.html?appid=b40d8277678949328b8f59332faa25e5

Map https://localgovdev.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=faadbdba39e64552a794561e920d4a30

The issue seems to happen with grouped layers. 

Workaround- use the classic map viewer or ungroup the layers in the new map viewer.

@GaneshDevarajan please take a look and give us LOE.

**Comment by sumitzarkar** [comment] 2022-11-17 06:20
@skrishn  


- This issue is related to Reporter issue [#526](https://github.com/Esri/crowdsource-reporter/issues/526)
- We have updated the code for CSM and CSR for this ticket. However, we see is some differences in the way how the visibility of the layers is maintained in the webmap when featureservice is added.
- In issue [#526](https://github.com/Esri/crowdsource-reporter/issues/526) for reporter , we got to know that - **_visibility is an optional property with an implicit default of true_**
- Whereas in this case, we are getting **undefined** value in the layers visibiity flag and undefined in JavaScript means false, the app is considering that the layer visibility for all the layers is false and hence we are not able to see any layers
 ![image](https://user-images.githubusercontent.com/9443956/202370739-eda1e2db-8cef-415d-af9c-083d84264ff3.png)
- We can fix this by changing the code to check the visibility value is false or true, before that it would be helpful if we get AGOL team's input if this expected to add visibility as undefined in webmap 
  
FYI - @aparveen

**Comment by aparveen** [comment] 2022-11-18 00:23
@sumitzarkar Map viewer team is saying there is not difference in the json between grouped and ungrouped layer. Is there something else going on in our app?
![image](https://user-images.githubusercontent.com/10148401/202588158-5ba19e29-3609-4095-9f43-29e4111bb1cd.png)

**Comment by sumitzarkar** [comment] 2022-11-22 05:29
@aparveen  @skrishn 

We analyzed this in more detail and here are our findings:
- We are using ArcGIS JS API to load the details of each webmap
- For this we are using [createmap method](https://developers.arcgis.com/javascript/3/jsapi/esri.arcgis.utils-amd.html#createmap) from JS API
- In response we get the itemInfo and itemData.
- So, the root cause is here, when we get the data using this method we see 'undefined' value in the visibility property of the operational layer
-  ![image](https://user-images.githubusercontent.com/9443956/202370739-eda1e2db-8cef-415d-af9c-083d84264ff3.png)

**Comment by aparveen** [comment] 2022-11-30 19:14
@sumitzarkar JS API team is fixing this issue

**Comment by aparveen** [comment] 2022-12-14 00:28
@sumitzarkar JS API team fixed it, the fix is in devext. Could you please see if you still getting undefined.
Test web map: https://sg-em-devext.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=f089c1f8545242ccb7bc5aa2742d597e

**Comment by sumitzarkar** [comment] 2022-12-19 04:52
@aparveen  - We checked in devExt and we don't see undefiend, and now the app is working as expected.

Please let us know if any action required from our end.

**Comment by aparveen** [comment] 2022-12-19 18:51
Thanks @sumitzarkar for looking into it.

**Closed by aparveen** 2022-12-19 18:51 UTC
Labels: Bug
